### ISSUE TITLE
please add your membership

### ISSUE THREAD

**Issue by mdsumner** [DataScienceHobart/studyGroup#2]
Fill out your details here by copying my lines (you'll get your github avatar by default): 

https://github.com/DataScienceHobart/studyGroup/blob/gh-pages/_data/members.yml

This will show up in the Who We Are section: http://datasciencehobart.github.io/studyGroup/

**Comment by tremenyi** [comment]
Done.

**Comment by bschroeter** [comment]
Done

**Comment by mhidas** [comment]
Done
